policy_path: "policy_stand_15dof.pt"

total_time: 1.0


kps: [100, 100, 100, 150, 40, 40,
      100, 100, 100, 150, 40, 40,
      200, 200, 200,
      100, 100, 50, 50, 20, 20, 20,
      100, 100, 50, 50, 20, 20, 20
      ]

kds: [2, 2, 2, 4, 2, 2,
      2, 2, 2, 4, 2, 2,
      5, 5, 5, 
      2, 2, 2, 2, 1, 1, 1,
      2, 2, 2, 2, 1, 1, 1
      ]

tau_limit: [88, 88, 88, 139, 50, 50,
            88, 88, 88, 139, 50, 50,
            88, 50, 50,
            25, 25, 25, 25, 5, 5, 5,
            25, 25, 25, 25, 5, 5, 5
           ]

default_angles: [-0.1,  0.0,  0.0,  0.3, -0.2, 0.0, 
                 -0.1,  0.0,  0.0,  0.3, -0.2, 0.0,
                  0, 0, 0,
                  0.35, 0.18, 0, 0.87, 0, 0, 0,
                  0.35, -0.18, 0, 0.87, 0, 0, 0,
                  ]

joint2motor_idx: [0, 1, 2, 3, 4, 5,
                  6, 7, 8, 9, 10, 11]

upper_body_motor_idx: [
  15, 16, 17, 18, 19, 20, 21,
  22, 23, 24, 25, 26, 27, 28
]

lower_body_motor_idx: [
  0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11,
  12, 13, 14,
]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
num_actions: 15
num_obs: 54 

upper_target_angles_skill_1: [
  0.35, 0.18, 0, 0.87, 0, 0, 0,
  0.35, -0.18, 0, 0.87, 0, 0, 0,
]

# upper_target_angles_skill_2: [
#   0.52135, 1.539432, 0.855396, 0.810539, 0, 0, 0,
#   0.516701, -1.508691, -1.27176, 0.717309, 0, 0, 0,
# ]

upper_target_angles_skill_2: [
  0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0,
]